use_frameworks!
source = 'https://https://github.com/MTS-LLC/JMap-iOS-SDK-Pod.git'

target 'OutdoorIndoorKit-iOS-Pod_Tests' do
  pod 'JMapiOSSDK'
  pod 'OutdoorIndoorKit-iOS-Pod', :path => '../'
  
end
